var StaticsHelper = function(app)
{
  this.app = app;
  this.packsMapping = {};
  this.cssBaseDir = '/css/css-gen/'; // css files generated by compass
  this.cssGenBaseDir = '/gen/css/'; // css files generated by compass and minified by optimizer r.js
  this.cssVgenBaseDir = '/vgen/css/'; // versionned css files generated by compass
  this.jsBaseDir = '/js/'; // normal js files
  this.jsGenBaseDir = '/gen/js/'; // js files minified and packed by optimizer r.js
  this.jsVgenBaseDir = '/vgen/js/'; // versionned js files minified and packed by optimizer r.js

  var fs = require('fs'),
    file = './build/ressource-mapping.json';

  var data = fs.readFileSync(file, {encoding: 'utf8'});

  this.packsMapping = JSON.parse(data);
}

StaticsHelper.prototype =
{
  cssPath: function(name)
  {
    if (this.app.locals.env == 'development')
    {
      return this.cssBaseDir + name + '.css';
    }
    else
    {
      return this.packsMapping['public' + this.cssGenBaseDir + name + '.css'].replace('public', '');
    }
  },
  jsPath: function(name)
  {
    if (this.app.locals.env == 'development')
    {
      return this.jsBaseDir + name + '.js';
    }
    else
    {
      return this.packsMapping['public' + this.jsGenBaseDir + name + '.js'].replace('public', '');
    }
  }
};

var staticHelperInstance = null;

module.exports = function(app)
{
  staticHelperInstance = new StaticsHelper(app);

  module.exports = staticHelperInstance;
}